name: Check configuration

on:
  push:
    branches:
      - "**" # Trigger the workflow on push to any branch
  pull_request: # Also trigger on pull requests
    branches:
      - "**" # Trigger the workflow on pull requests to any branch
  workflow_dispatch: # Allows you to manually trigger the workflow

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Clone the Go project repository
      - name: Clone Go Project Repository
        run: |
          git clone --depth 1 https://github.com/shallowBunny/app.git
          cd app/be

      # Step 3: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Specify the Go version you want to use

      - name: Build the project
        run: |
          cd app/be
          make build  # Run the build command

      # Step 4: Run config check
      - name: Run config check
        id: check_config
        continue-on-error: true
        run: |
          cd app/be          
          if ! ./shallowBunny -config=../../config.yml -check > config_output.txt 2>&1; then
            echo "Error: shallowBunny failed. Printing output:"
            cat config_output.txt
            exit 1
          fi
      # Step 5: Comment on PR
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('app/be/config_output.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Result of \`./shallowBunny -config=../../config.yml -check\`:\n\n\`\`\`\n${output}\n\`\`\``
            })
